name = "prisma-example"
main = "src/index.js"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "prisma-example"
database_id = "11d425e0-c225-4342-895b-47af4b7337d6"

[dev]
port = 4444